// How a page's worth of photos is arranged into rows, in one place.
//
// A project page has no page breaks: apps/api/src/domains/projects/page-pdf.ts
// draws <hr> as a rule and fills sheets by flowing content, so "photos per
// page" is really "photos in this group, laid out to fill a sheet". Three
// separate places had independently decided what that means:
//
//   the editor's Insert menu   tiptap-photo-slot.ts, 1/2/3-up plus 2x2 for four
//   the seeded SQL templates   the same widths, written by hand per template
//   the Report generator       four across at a quarter width each
//
// The last one was wrong, and visibly so: four photos squeezed into one row are
// a strip of thumbnails, not a page of evidence. The editor had already made
// the right call and written down why. This module is that call, extracted, so
// a document generated by AI and a document a user built by hand come out
// looking like the same product.

/** Percentage width per photo so a row fills the content column without wrapping. */
export const PHOTO_ROW_WIDTH: Record<1 | 2 | 3 | 4, string> = {
  1: "100%",
  2: "48%",
  3: "32%",
  4: "48%",
};

/** Slot and photo height, matched to the seeded templates' art. */
export const PHOTO_ROW_HEIGHT = 280;

/**
 * Split `items` into the rows that make up each page group.
 *
 * Four-up is two stacked rows of two, not one four-wide row, so each photo
 * stays a readable size. Every other density is one row per group. The result
 * is a flat list of rows, in reading order.
 */
export function photoRows<T>(items: readonly T[], perPage: 1 | 2 | 3 | 4): T[][] {
  const rows: T[][] = [];
  const rowSize = perPage === 4 ? 2 : perPage;
  for (let i = 0; i < items.length; i += rowSize) {
    rows.push(items.slice(i, i + rowSize));
  }
  return rows;
}

/**
 * Split `items` into page groups: the photos that belong together on a sheet,
 * each already divided into its rows.
 *
 * `photoRows` alone loses the group boundary, which is what a caption block or
 * a card needs to wrap - at four-up the two rows of two are one group, not two.
 */
export function photoPageGroups<T>(items: readonly T[], perPage: 1 | 2 | 3 | 4): T[][][] {
  const groups: T[][][] = [];
  for (let i = 0; i < items.length; i += perPage) {
    groups.push(photoRows(items.slice(i, i + perPage), perPage));
  }
  return groups;
}
