// How a page's worth of photos is arranged into rows, in one place.
//
// A project page has no page breaks: apps/api/src/domains/projects/page-pdf.ts
// draws <hr> as a rule and fills sheets by flowing content, so "photos per
// page" is really "photos in this group, laid out to fill a sheet". Three
// separate places had independently decided what that means:
//
//   the editor's Insert menu   tiptap-photo-slot.ts, 1/2/3-up plus 2x2 for four
//   the seeded SQL templates   the same widths, written by hand per template
//   the Report generator       four across at a quarter width each
//
// The last one was wrong, and visibly so: four photos squeezed into one row are
// a strip of thumbnails, not a page of evidence. The editor had already made
// the right call and written down why. This module is that call, extracted, so
// a document generated by AI and a document a user built by hand come out
// looking like the same product.

/**
 * Percentage width per photo so a row fills the content column without
 * wrapping. Indexed by how many share the row, NOT by the per-page setting -
 * four-up in "slots" mode lays out as rows of two, so it wants the two-up
 * width.
 */
export const PHOTO_ROW_WIDTH: Record<1 | 2 | 3 | 4, string> = {
  1: "100%",
  2: "48%",
  3: "32%",
  4: "23%",
};

/** The width each photo takes at a given per-page setting and mode. */
export function photoWidthFor(perPage: 1 | 2 | 3 | 4, mode: PhotoRowMode = "slots"): string {
  const perRow = mode === "slots" && perPage === 4 ? 2 : perPage;
  return PHOTO_ROW_WIDTH[perRow as 1 | 2 | 3 | 4];
}

/** Slot and photo height, matched to the seeded templates' art. */
export const PHOTO_ROW_HEIGHT = 280;

/**
 * Whether four-up means a 2x2 grid or one four-wide row.
 *
 * The two callers genuinely want different things, and pretending otherwise
 * produced a control that did not work:
 *
 *   "slots"   Empty click-to-fill boxes in a template. Four across would be a
 *             quarter-width tap target, so four-up stacks as 2x2. Density is
 *             not the point; hitting the box is.
 *
 *   "photos"  Finished evidence in a generated report. Here density IS the
 *             point, and 2x2 broke it: measured on a rendered PDF, four-up put
 *             four photos on a sheet at 248pt wide - the same as two-up, and
 *             FEWER than three-up's six at 163pt. Every step of a control
 *             labelled 1 to 4 has to fit more than the step below it.
 *
 * apps/api/src/domains/projects/page-pdf.ts is what forces the distinction: its
 * `renderImageRow` ignores the width attribute entirely and divides the content
 * column evenly between however many images share a paragraph. Images per
 * paragraph is therefore the only lever either renderer has.
 */
export type PhotoRowMode = "slots" | "photos";

/**
 * Split `items` into the rows that make up each page group, in reading order.
 */
export function photoRows<T>(
  items: readonly T[],
  perPage: 1 | 2 | 3 | 4,
  mode: PhotoRowMode = "slots",
): T[][] {
  const rowSize = mode === "slots" && perPage === 4 ? 2 : perPage;
  const rows: T[][] = [];
  for (let i = 0; i < items.length; i += rowSize) {
    rows.push(items.slice(i, i + rowSize));
  }
  return rows;
}

/**
 * Split `items` into page groups: the photos that belong together on a sheet,
 * each already divided into its rows.
 *
 * `photoRows` alone loses the group boundary, which is what a caption block or
 * a card needs to wrap - in "slots" mode the two rows of two are one group,
 * not two.
 */
export function photoPageGroups<T>(
  items: readonly T[],
  perPage: 1 | 2 | 3 | 4,
  mode: PhotoRowMode = "slots",
): T[][][] {
  const groups: T[][][] = [];
  for (let i = 0; i < items.length; i += perPage) {
    groups.push(photoRows(items.slice(i, i + perPage), perPage, mode));
  }
  return groups;
}
