-- Put the project's name on the documents that were filed without one.
--
-- The client, looking at a document he had just created from a template:
--
--   "the template name is the same name as the name it has in the Document
--    templates ... this gets auto saved into that project under documents and
--    the same name as the document template ... right now it confusingly saves
--    under that project under generic template name and forces the user to
--    change the name to stay organized."
--
-- He is right, and the cause was one line: `createPageFromTemplateService` wrote
-- `title: template.name` verbatim. The three other routes that create a document
-- were no better, each inventing its own default and none of them naming the
-- job:
--
--   from a template   HVAC Service Call Report
--   generated by AI   Report - 8/17/2026
--   blank page        Untitled
--
-- apps/api/src/domains/projects/page-title.ts now names all four after the
-- project. That fixes every document made from here on and not one of the
-- documents already sitting in the app, which is the half the client is actually
-- looking at.
--
-- It does not stay inside the app, either. `renderPagePdf` builds the download
-- filename out of this title, so the customer on the other end has a folder of
-- `HVAC_Service_Call_Report.pdf` and `Report_-_8_17_2026.pdf` with nothing to
-- say which site any of them covers.
--
-- ---------------------------------------------------------------------------
-- WHAT THIS RENAMES, AND WHAT IT WILL NOT TOUCH
-- ---------------------------------------------------------------------------
-- Only a title that is still byte-identical to the default the app assigned it.
-- That is the whole safety rule, and it is the same one 20260903000000 used to
-- decide which templates were safe to retire: identical to what the machine
-- wrote means no human has been near it, so nothing anyone typed is at risk.
--
--   1. Created from a document template, and the title is still exactly that
--      template's name.
--   2. Generated with AI, and the title is still exactly "Daily Log - <date>",
--      "Summary - <date>" or "Report - <date>" with a numeric date.
--   3. Titled exactly "Untitled", whatever made it.
--
-- A document somebody renamed - even to something that looks generic, even to
-- another template's name - fails all three and is left alone. So is a document
-- whose project has no name, and one whose title already opens with the project
-- name, which is what makes this safe to run twice: after a rename none of the
-- three rules match it any more.
--
-- The 200 character cap is not cosmetic. `updateProjectPage` and
-- `createProjectPage` both cap `title` at 200, and the editor sends the title
-- with every autosave - so a 205 character title written here would make the
-- next body edit on that document fail validation and silently drop the user's
-- typing. The project name is what gets shortened to fit, never the document's
-- own name, and a row with no room for a meaningful prefix is skipped instead.
--
-- Apply via the SitePix Supabase SQL editor (or `supabase db push`).

SET lock_timeout = '5s';

-- =========================================================================
-- 0. QUIET THE updated_at TRIGGER
-- =========================================================================
-- `trg_project_pages_updated_at` stamps `updated_at = now()` on any UPDATE, and
-- the Documents tab sorts by `updated_at DESC`. Left alone, this migration would
-- reorder every project's document list into migration order and present a
-- year of finished paperwork as edited today. The date a document was last
-- worked on is real information; a rename is not an edit to it.
--
-- Disabled rather than dropped, and restored in section 2. `ALTER TABLE ...
-- DISABLE TRIGGER` is transactional and a migration runs as one transaction, so
-- a failure anywhere below rolls the disable back with everything else. There is
-- no state in which this leaves the trigger off.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_trigger
              WHERE tgrelid = 'public.project_pages'::regclass
                AND tgname = 'trg_project_pages_updated_at') THEN
    ALTER TABLE public.project_pages DISABLE TRIGGER trg_project_pages_updated_at;
  END IF;
END $$;

-- =========================================================================
-- 1. RENAME
-- =========================================================================
-- Procedural rather than one clever UPDATE, because the numbering has to see
-- the rows this same statement has already written: two documents in one
-- project can carry the same machine-assigned title today, and renaming both to
-- the same new one would move the collision rather than resolve it. Each
-- iteration's UPDATE is visible to the next iteration's EXISTS, so the second
-- one lands as "(2)".
--
-- The volume is small by construction - one row per document ever created, and
-- only those never renamed.
DO $$
DECLARE
  _row      record;
  _project  text;
  _base     text;
  _stem     text;
  _title    text;
  _room     int;
  _n        int;
  _renamed  int := 0;
  _skipped  int := 0;
BEGIN
  FOR _row IN
    SELECT p.id, p.project_id, p.title, pr.name AS project_name
      FROM public.project_pages p
      JOIN public.projects pr ON pr.id = p.project_id
     WHERE
       -- 1. Still carrying the exact name of the template it was made from.
       --    `source_template` holds `document_template:<uuid>` for these
       --    (see documentTemplateId in apps/api/src/domains/projects/pages.ts).
       EXISTS (
         SELECT 1 FROM public.document_templates t
          WHERE p.source_template = 'document_template:' || t.id::text
            AND btrim(p.title) = btrim(t.name)
       )
       -- 2. Still carrying the generated default. The date is whatever
       --    `toLocaleDateString()` produced, so the pattern accepts any numeric
       --    spelling of one and nothing else: a title with a word in it has been
       --    touched by a person and is not ours to rewrite.
       OR (p.source_template IN ('daily_log', 'summary', 'report')
           AND btrim(p.title) ~ '^(Daily Log|Summary|Report) - [0-9][0-9/.-]*$')
       -- 3. Never named at all.
       OR btrim(p.title) = 'Untitled'
     ORDER BY p.project_id, p.created_at, p.id
  LOOP
    _project := btrim(COALESCE(_row.project_name, ''));
    _base := btrim(_row.title);

    -- A project with no name of its own has no hint to lend.
    IF _project = '' THEN
      _skipped := _skipped + 1;
      CONTINUE;
    END IF;

    -- Already says which job it is. This is also what makes a second run a
    -- no-op on every row the first run renamed.
    --
    -- `starts_with` rather than `LIKE lower(_project) || '%'`: a project called
    -- "50_Main St" or "Kitchen 100%" carries LIKE metacharacters in its own
    -- name, and matching them as wildcards would skip renames that should have
    -- happened.
    IF starts_with(lower(_base), lower(_project)) THEN
      _skipped := _skipped + 1;
      CONTINUE;
    END IF;

    -- The document's own name is the half that says what it IS, so the project
    -- name is the half that gets shortened, and below eight characters of it
    -- there is no hint left to give - only a stub that reads like damage.
    _room := 200 - length(_base) - 3;
    IF _room < 8 THEN
      _skipped := _skipped + 1;
      CONTINUE;
    END IF;
    IF length(_project) > _room THEN
      _project := rtrim(left(_project, _room));
    END IF;

    _stem := _project || ' - ' || _base;
    _title := _stem;
    _n := 1;
    -- Numbered, not "(copy)": a second visit to the same job is not a copy of
    -- the first one. Matches uniqueDocumentTitle in page-title.ts.
    WHILE EXISTS (
      SELECT 1 FROM public.project_pages o
       WHERE o.project_id = _row.project_id
         AND o.id <> _row.id
         AND lower(btrim(o.title)) = lower(_title)
    ) LOOP
      _n := _n + 1;
      _title := CASE
        WHEN length(_stem) + length(' (' || _n || ')') > 200
          THEN rtrim(left(_stem, 200 - length(' (' || _n || ')'))) || ' (' || _n || ')'
        ELSE _stem || ' (' || _n || ')'
      END;
    END LOOP;

    UPDATE public.project_pages SET title = _title WHERE id = _row.id;
    _renamed := _renamed + 1;
  END LOOP;

  RAISE NOTICE 'project_pages titles: % renamed, % left alone', _renamed, _skipped;
END $$;

-- =========================================================================
-- 2. RESTORE THE TRIGGER
-- =========================================================================
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_trigger
              WHERE tgrelid = 'public.project_pages'::regclass
                AND tgname = 'trg_project_pages_updated_at') THEN
    ALTER TABLE public.project_pages ENABLE TRIGGER trg_project_pages_updated_at;
  END IF;
END $$;

-- Nothing below this line may be left disabled. Fails loudly rather than handing
-- back a database whose documents have quietly stopped recording when they were
-- last edited.
DO $$
DECLARE
  _off text;
BEGIN
  SELECT string_agg(tgname::text, ', ') INTO _off
    FROM pg_trigger
   WHERE tgrelid = 'public.project_pages'::regclass
     AND NOT tgisinternal
     AND tgenabled = 'D';
  IF _off IS NOT NULL THEN
    RAISE EXCEPTION 'Migration finished with triggers still disabled: %', _off;
  END IF;
END $$;

-- === VERIFY ================================================================
-- Worth running BEFORE this file, as a preview: it selects exactly the rows
-- section 1 will rewrite, with the name each of them would take. Change the
-- WHERE to `= p.title` afterwards and it should come back empty.
--
-- SELECT pr.name AS project, p.title AS current_title,
--        left(btrim(pr.name) || ' - ' || btrim(p.title), 200) AS becomes
--   FROM public.project_pages p
--   JOIN public.projects pr ON pr.id = p.project_id
--  WHERE btrim(COALESCE(pr.name, '')) <> ''
--    AND NOT starts_with(lower(btrim(p.title)), lower(btrim(pr.name)))
--    AND (EXISTS (SELECT 1 FROM public.document_templates t
--                  WHERE p.source_template = 'document_template:' || t.id::text
--                    AND btrim(p.title) = btrim(t.name))
--         OR (p.source_template IN ('daily_log', 'summary', 'report')
--             AND btrim(p.title) ~ '^(Daily Log|Summary|Report) - [0-9][0-9/.-]*$')
--         OR btrim(p.title) = 'Untitled')
--  ORDER BY pr.name, p.title;
--
-- No title may exceed 200 characters. Over that, the editor's own autosave
-- would fail validation and drop whatever the user had just typed into the body,
-- so this is the one to check after a run. It should return no rows:
--
-- SELECT id, project_id, length(title) AS len, title
--   FROM public.project_pages WHERE length(title) > 200;
--
-- Documents that still share a title inside one project. Not an error - the
-- column has never been unique, and two rows a person deliberately named alike
-- are their filing decision - but after this runs the machine is no longer
-- contributing any of them:
--
-- SELECT project_id, lower(btrim(title)) AS title, count(*)
--   FROM public.project_pages
--  GROUP BY 1, 2 HAVING count(*) > 1 ORDER BY 3 DESC;
--
-- And nothing may be left disabled - `tgenabled` is 'O' for a live trigger:
--
-- SELECT tgname, tgenabled FROM pg_trigger
--  WHERE tgrelid = 'public.project_pages'::regclass AND NOT tgisinternal;
